### ISSUE TITLE
Is it possible to consider album duration when calculating the score?

### ISSUE THREAD

**Issue by rabelux** [seanap/Audiobooks.bundle#34]
I think if an album's duration could be matched other information like narrator and ASIN don't have to be used as duration should be pretty explicit.
In an [ancient framework documentation from plex](https://forums.plex.tv/t/plugin-development-documentation/107751/2), page 60, `duration` is listed as an album's property but I wasn't able to access it.
As I'm just a hobby programmer I'm not able to dig any further but I wanted to throw in this idea.

**Comment by seanap** [comment]
If the books we are adding are from Audible, then this makes 100% sense.  I use duration to help (manually) match books against audible in mp3tag all the time.  That said, for books not in audible, slightly different versions than what audible has (narrators, editions, abridged, source, etc), I wouldn't want the duration to mess with finding the "best match".  Something like: all-other-things-being-equal prefer the release with the most similar duration.

I've just come across so many books that don't match the duration from Audible.  Maybe my source files are missing a chapter, maybe the encoding went wrong, or maybe the audible release included or removed parts, who knows, but it happens enough that I can't expect the times to always be consistent (maybe 80% of the durations match?)

**Comment by rabelux** [comment]
Agreed.
That's why I was wondering if we could use that information to recalc the score.
Like if durations differ by 10 % deduct 5 points, 25 % 20 points and so on.

**Comment by seanap** [comment]
I think this may help avoid some situations where we have multiple matches with the same score. That said, I have come across books that audible only has the abridged version (or I only have the executive summaries) so the duration would be off by 14+hrs, but I still want all the metadata. So we have to be careful that being way off doesn't effect too much.

**Comment by djdembeck** [comment]
2 thoughts on why this won't be possible:

- Plex docs note `duration` as being for movie and tv only:
![Screenshot_20210923-120948.jpg](https://user-images.githubusercontent.com/71412966/134553066-24f7aa05-31b7-4a96-a84e-54f4be0db2da.jpg)
- Mixed user storage methods. A lot of people store multiple files for a book, as their chapter markers. My guess is, that's why Plex states the above note.

As far as I can tell, we don't have access to file metadata natively. I'm sure someone could creatively write a workaround. However, that's a lot of time spent on an ultimately imperfect scoring system.

**Comment by rabelux** [comment]
Alright. I'll close this then.
