### ISSUE TITLE
everything works fine, but it doesn't download the book image

### ISSUE THREAD

**Issue by shafai** [seanap/Audiobooks.bundle#5]
I've set it up and works perfectly fine, It just doesn't download the "poster". anything extra I should do to set it up?

**Comment by csandman** [comment]
I came to say the same thing, the only issue I'm having is with the cover, everything else seems to work great

**Comment by seanap** [comment]
Before adding any files into plex I first run it through mp3tag to scrape Audible and set all the tags and add the poster to the metadata.  In plex I actually set up the library to "Prefer embedded artwork".  The reason I do things this way is because I have had a handful of server rebuilds over the years and I hated tagging everything in plex only to lose it all, so now I tag everything in the file and feel more comfortable that plex/agent can't mess things up.

I do the same thing with genres, I set the genres to what I want in the file and I have plex read the embedded data. Same with Title and Author, because this agent is doing basic webscraping and not database lookup the matches can occasionally be incorrect and it becomes crazy hard to identify mismatched items with large collections.  Therefore, I assume that you are giving plex properly tagged files.  My mp3tag web source script also uses basic webscrapping to grab the data from audible, however, you have the chance to review and modify all tags on a book-by-book basis. Trust me I wish there were a more reliable way, but until there is a tvdb or tmdb for audiobooks this was the best way for me to ensure that my plex data was reliable (even if you had to rebuild from scratch).

To change this behavior open the _init_.py file and you can see where I've commented out the genres, narrators in genres, title, author, and poster, starting on lines 570 - 584.  To re-add this functionality for the posters just delete the "#" on lines 580 and 581.

**Comment by csandman** [comment]
My issue with this is that it doesn't even use the embedded cover, even with the option set to "Local Files Only" unless I unmatch and match again.  Not really sure what's up with it.

**Comment by csandman** [comment]
Ah I figured it out, I must have missed the step (https://github.com/seanap/Plex-Audiobook-Guide#configure-metadata-agent-in-plex) where I was supposed to set the Albums part of the metadata agents to prefer local files!
